### ISSUE TITLE
Code inside <code> disappears after save & refresh in editor when using HTML output

### ISSUE THREAD

**Issue by DanielSpravtsev** [awcodes/filament-tiptap-editor#444]
### Filament Version

v3.2.98

### Plugin Version

3.4.8

### PHP Version

8.3.1

### Problem description

Code inside code blocks wipes out to first word when using default HTML output after save and refresh in filament resource create
When using JSON output everything is ok, so I think there are some issues in code blocks formatting, maybe coming from tiptap dependency itself

![2024-08-12_12-13-44](https://github.com/user-attachments/assets/af75ac5a-16ee-4fa9-b615-8b352efbdafa)
After save & refresh:
![2024-08-12_12-14-11](https://github.com/user-attachments/assets/ea822dc4-3cca-40dc-ab27-c3fe88f24f8e)

### Expected behavior

Code should not disappear

### Steps to reproduce

Create new resource record
Paste code block to editor
Press save
Refresh page
Code will wiped to the first starting word

**Comment by awcodes** [comment]
Thinking this could be related: https://github.com/awcodes/filament-tiptap-editor/issues/384

**Comment by DanielSpravtsev** [comment]
> Thinking this could be related: https://github.com/awcodes/filament-tiptap-editor/issues/384


This could fix it

1.4.0 
https://github.com/ueberdosis/tiptap-php/releases

**Comment by awcodes** [comment]
Nice, was waiting on a update from them.  Will look into bumping it soon. You should be able to bump it in your project though without having to wait on me.

**Comment by awcodes** [comment]
Looks like the problem still isn't solved. But I'm unable to replicate your exact issue. I'll do some more digging.

**Comment by ankitcodes4u** [comment]
I have also encountered this vanishing code problem but my one looks like this.

https://github.com/user-attachments/assets/52aa8487-018d-4256-a6c5-ffe7052dc5ef

Here I have created a custom block. If I add some other element infront of custom block everything works. But if my code start with that custom block followed by regualre element when I try to clear the regular element only the block disappears.

**Comment by ankitcodes4u** [comment]
And some times if I save only the custom block in the field. It disappears when I save and come back to see it again.

**Comment by awcodes** [comment]
Yea. There's something odd going on with custom nodes as the first element of the schema. Unfortunately, I have been able yet to track down if it's an issue with Tiptap itself or the plugin.

**Comment by fabianpimminger** [comment]
@awcodes Unfortunately I'm having the same issue. Any idea whats wrong here?

**Comment by awcodes** [comment]
No update yet. Sorry.

**Comment by awcodes** [comment]
Possibly resolved with v3.4.14. Let me know.

**Comment by fabianpimminger** [comment]
@awcodes it's working in 3.4.14! Thank you very much!

**Comment by gergo-tar** [comment]
@awcodes I am still having this problem
I am using the latest version (v3.4.16).
The filament version: v3.2.115 

[Screencast 2024-10-05 10:06:19.webm](https://github.com/user-attachments/assets/433890bf-5d65-4ada-877e-4f2e0e40e8e0)

This is the example source code:
`<p><span style="font-size:12pt;font-family:Roboto,sans-serif;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">After install, verify your PHP version:</span></p><pre class="hljs"><code>php -v</code></pre><p><span style="font-size:12pt;font-family:Roboto,sans-serif;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">To <strong>explore more PHP modules</strong> for your Laravel projects, use the following command:</span></p><pre class="hljs"><code class="language-css">sudo apt search php8.3-</code></pre>`

The weird thing is that not every code block is affected. And it seems to happen when I edit the content between the code blocks.
Here for example only the 2nd and 4th are partly disappeared: 
![image](https://github.com/user-attachments/assets/a483afdc-bb6b-4367-8e6b-01e541b28c37)

After editing:
![image](https://github.com/user-attachments/assets/008ae5a8-457e-4403-b9a0-5b8d4814c6b6)

**Comment by DanielSpravtsev** [comment]
> @awcodes I am still having this problem
> 
> I am using the latest version (v3.4.16).
> 
> The filament version: v3.2.115 
> 
> 
> 
> [Screencast 2024-10-05 10:06:19.webm](https://github.com/user-attachments/assets/433890bf-5d65-4ada-877e-4f2e0e40e8e0)
> 
> 
> 
> This is the example source code:
> 
> `<p><span style="font-size:12pt;font-family:Roboto,sans-serif;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">After install, verify your PHP version:</span></p><pre class="hljs"><code>php -v</code></pre><p><span style="font-size:12pt;font-family:Roboto,sans-serif;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">To <strong>explore more PHP modules</strong> for your Laravel projects, use the following command:</span></p><pre class="hljs"><code class="language-css">sudo apt search php8.3-</code></pre>`
> 
> 
> 
> The weird thing is that not every code block is affected. And it seems to happen when I edit the content between the code blocks.
> 
> Here for example only the 2nd and 4th are partly disappeared: 
> 
> ![image](https://github.com/user-attachments/assets/a483afdc-bb6b-4367-8e6b-01e541b28c37)
> 
> 
> 
> After editing:
> 
> ![image](https://github.com/user-attachments/assets/008ae5a8-457e-4403-b9a0-5b8d4814c6b6)
> 
> 

I just switched everything to json output with conversion to html at blade and forget about this issue. You could also do the same 🙂

**Comment by awcodes** [comment]
So, it's not an issue? Idk 🤷

**Comment by gergo-tar** [comment]
Thanks @DanielSpravtsev, I changed the output to `TiptapOutput::Json` and I do not have this problem.
@awcodes the issue occurs only when I change the format for saving to `TiptapOutput::Html`

But it is not an issue for me anymore since I moved to json.

> > @awcodes I am still having this problem
> > I am using the latest version (v3.4.16).
> > The filament version: v3.2.115
> > 
> >   
> >     
> >     
> > 
> >     Screencast.2024-10-05.10.06.19.webm
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > This is the example source code:
> > `<p><span style="font-size:12pt;font-family:Roboto,sans-serif;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">After install, verify your PHP version:</span></p><pre class="hljs"><code>php -v</code>\</pre\><p><span style="font-size:12pt;font-family:Roboto,sans-serif;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">To \<strong\>explore more PHP modules\</strong\> for your Laravel projects, use the following command:</span></p><pre class="hljs"><code class="language-css">sudo apt search php8.3-</code>\</pre\>`
> > The weird thing is that not every code block is affected. And it seems to happen when I edit the content between the code blocks.
> > Here for example only the 2nd and 4th are partly disappeared:
> > ![image](https://private-user-images.githubusercontent.com/13517318/373857054-a483afdc-bb6b-4367-8e6b-01e541b28c37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzc3NDYsIm5iZiI6MTcyODM3NzQ0NiwicGF0aCI6Ii8xMzUxNzMxOC8zNzM4NTcwNTQtYTQ4M2FmZGMtYmI2Yi00MzY3LThlNmItMDFlNTQxYjI4YzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OGYzZjU3ODQxN2FhYTc2ZDA1MGY1MDU3OTgzMmZmYzhiMDRmZTIzZGMxZDMyODJlZWY3Y2ZjOWViNzBlZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6EbVKTC8VJHz-_zTBFJIsed0OxaDUFY_RP2kcPBd8pg)
> > After editing:
> > ![image](https://private-user-images.githubusercontent.com/13517318/373857289-008ae5a8-457e-4403-b9a0-5b8d4814c6b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzc3NDYsIm5iZiI6MTcyODM3NzQ0NiwicGF0aCI6Ii8xMzUxNzMxOC8zNzM4NTcyODktMDA4YWU1YTgtNDU3ZS00NDAzLWI5YTAtNWI4ZDQ4MTRjNmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YTUxYmIwODE1MDhmODY3MzBlZjJiOGM0NTg5MTIwNTRmMTc3M2JjMjIzOGM4ODU2ZjJjYWZiOTlhZDhjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KSIiucoL0Ms-9-38fiME4e1tNoToAjgcd2ebOEnvPGg)
> 
> I just switched everything to json output with conversion to html at blade and forget about this issue. You could also do the same 🙂

**Comment by IgorDePaula** [comment]
For me dont works.
