### ISSUE TITLE
Grid bug (duplicating blocks)

### ISSUE THREAD

**Issue by aboutnima** [awcodes/filament-tiptap-editor#585]
### Filament Version

v3.4

### Plugin Version

v3.0

### PHP Version

v8.2.26

### Problem description

Block duplicate when moving it out from `gridColumn` and try to edit it immediately.

### Expected behavior

Block should not duplicate

### Steps to reproduce

1. Add any block into editor
2. Add `grid` with 3 columns after first created block
3. Add another new block into one of 3 provided `columns`
4. Move out the block from `column`
5. Try to edit the block "For example its label"
6. When you submit edit dialog, block will be duplicated

### Relevant log output

```shell

```

**Comment by awcodes** [comment]
Can you provide a reproduction repo? I can't replicate the issue in my demo app.

**Comment by aboutnima** [comment]
There is no need for reproduction repo. I can send you a video for that

https://github.com/user-attachments/assets/884f8dc0-5005-4d83-988d-73aedeb1d394

**Comment by awcodes** [comment]
What's the exact version of the plugin you are using? Also you missed some steps during the installation, that's why the editor looks the way it does.

But I will still need a reproduction repo to try to help since I can't replicate the isssue.

**Comment by aboutnima** [comment]
Ohh. Ok i will reinstall it. Give me some minutes I think I had a reproduction repo for `filament-tiptap-editor`. I will share the repo ASAP!

**Comment by aboutnima** [comment]
here is the repo: [https://github.com/aboutnima/awcodes-filament](https://github.com/aboutnima/awcodes-filament)

Go to _/admin/forms/create_ and act exact like video I have sent

Used version is 3.4.19

**Comment by awcodes** [comment]
Tested with your repo and the problem doesn't exist. My guess is that you need to update the plugin to the latest version.

**Comment by aboutnima** [comment]
I double checked it before sharing the repo and the bug was still there. Is there any chance for me to check it on your reproduction repo?

I am going to update the plugin to latest version to check it again.

**Comment by awcodes** [comment]
What I'm saying is that 3.4.19 may have the bug you're experiencing but latest is 3.5.10 which probably has a fix from a previous version. So updating the plugin with composer should resolve the issue.

**Comment by aboutnima** [comment]
I update and reinstall the package by following the document. I'm still facing the issue even due I'm using document example block.
The version that I'm using is `3.5.11`

**Comment by aboutnima** [comment]
Update!

I have been digging into the package and trying to solve the issue. I discovered something. After reading `Tiptap Editor` document, I realized the `insertContentAt` method replaces new content (or block) with the given range.

Look at this screenshot below:

<img width="1180" alt="Image" src="https://github.com/user-attachments/assets/fb134040-937f-4b4f-991f-09dd9df022e5" />

I have been `console.log($from.pos, $to.pos)` and got the same position for both blocks. (The positions are incorrect sometimes).
My best guess is the problem related `grid`. After a block is dragged into a grid or dragged out, `$from.pos` and `$to.pos` stay the same and they don not update.

**Comment by awcodes** [comment]
Ok, but if this isn't replicatable in your repo, which I installed and tested then the issue is somewhere in your app and not the plugin itself. I want to help but I'm at a loss since I can't replicate it even with your repo. Are you seeing any console errors in dev tools?

**Comment by awcodes** [comment]
Closing as stale
