### ISSUE TITLE
Content not updating when switching locales with filament/spatie-laravel-translatable-plugin

### ISSUE THREAD

**Issue by naramalkoht** [awcodes/filament-tiptap-editor#85]
When using filament/spatie-laravel-translatable-plugin in conjunction with spatie/laravel-translatable, the content of the editor does not update when switching locales using the locale switcher from spatie/laravel-translatable. Specifically, after switching the locale, the content remains the same and does not reflect the updates made for the newly selected locale.

Versions

- PHP 8.1
- awcodes/filament-tiptap-edito : 2.2.3
- filament/filament : 2.17.9
- laravel/framework : 10.1.5

**Comment by awcodes** [comment]
Seems like a regression. Will try to solve tomorrow.

**Comment by chiiya** [comment]
Seems like it only switches correctly for the first instance? When having multiple `TiptapEditor` fields in a form, only the first one switches locale correctly.

I'm on the latest version (2.2.10)

**Comment by awcodes** [comment]
Should be fixed with v2.2.11.

**Comment by NicoLeroyDev** [comment]
Hello !

I still have a strange behaviour using :
awcodes/filament-tiptap-editor v2.2.11
filament/spatie-laravel-translatable-plugin v2.17.40

I have to switch many times before the tiptap editor actually reloads properly...

I have 2 languages, french and english.

On first page load :
Switch and editor both in English, that's good.
I switch to french -> editor still in english.
I switch back to english -> editor still in english (which is good)
I switch back again to french -> editor in french (which is good)

And then I have to repeat the same process to display the editor in english.

The same behaviour occurs either if I have only one editor, or many...

Edit :
Sorry, in `config/app.php`, I had this : `'locale' => 'fr'`. Setting this to `'en'` fixed my problem, even if I would prefer keep it like it was ^^...

**Comment by awcodes** [comment]
Ok. let me do some more digging. It should be respecting the app's default locale too.

**Comment by chiiya** [comment]
Yea, it seems to skip the first language switch. I have 3 languages:
- Defaults to English and displays English content, which is good
- I switch to German -> nothing happens
- I switch to French -> content switches to German (previous selection)
- I switch to English -> content switches to French (previous selection)
etc.

**Comment by awcodes** [comment]
Hmm. I can't replicate the issue. Only thing i'm seeing is that the language switcher doesn't honor the default locale, but that comes down to the order you in which you register the available locales for the resource.

This is with `locale => 'fr'` in `app/config.php`.


https://github.com/awcodes/filament-tiptap-editor/assets/3596800/db7767cd-b7e6-4546-bd11-3aebdcdd50a9

**Comment by chiiya** [comment]
It only happens with a sufficiently high amount of editor instances. 

On my form I originally had 26 TipTapEditors. Locally, it was working fine, however on the staging server the aforementioned issue kept showing up. Once I started adding even more fields (40-50+) I could also observe the same error locally. Not consistently every time, but sometimes the language switch just doesn't update the editor content.

Weirdly enough, the same doesn't happen with the default Filament `RichEditor`, it just seems to be some kind of overhead this package adds.

Unfortunately I can't spend any more time on researching this error, so I switched to the [tiny-editor](https://github.com/mohamedsabil83/filament-forms-tinyeditor) plugin for now, which doesn't have this issue.
